### ISSUE TITLE
Getting WER worse than expected

### ISSUE THREAD

**Issue by mjhanphd** [rwth-i6/returnn-experiments#13]
Hi
I tested on my own [2018-asr-atention/librispeech/full-setup-attention](https://github.com/rwth-i6/returnn-experiments/tree/master/2018-asr-attention/librispeech/full-setup-attention) and I've got WER score of 4.82 on librispeech test-clean data as below.

```
(tensorflow3.5) [myoungji.han@eodssr1 exp-returnn]$ cat search.test-clean.ep250.beam12.recog.scoring.wer
4.82
```

This is worse than your reported score of 3.82.
I hope you can give me a clue if there is something wrong.
Thank you in advance.

**Comment by albertz** [comment]
The 3.82% WER on test-clean is done with a LSTM LM.
full-setup-attention currently is without a LM.
You find the configs to use the attention model together with a LM [here](https://github.com/rwth-i6/returnn-experiments/tree/master/2018-asr-attention/librispeech/lm).
