### ISSUE TITLE
Have you tried multi-head attention on Librispeech?

### ISSUE THREAD

**Issue by mjhanphd** [rwth-i6/returnn-experiments#14]
Hi
I found that I can give multi-head attention attributes with config file. (AttNumHeads)
Have you tried AttNumHeads greater than 1 for asr on librispeech?
I wonder if the rather bad performance on test-other dataset could be alleviated by multi-head attention.
Thank you in advance :)

**Comment by albertz** [comment]
Yes I tried, but it was worse.
