### ISSUE TITLE
Audio + Text embedding alignment

### ISSUE THREAD

**Issue by MartinLichtblau** [rwth-i6/returnn-experiments#15]
Is it possible to create a vector space containing words in textual and audio form and alignigning them so that both share the same vector representation? 
The idea is that text-word-embeddings could be improved in further steps.

**Comment by albertz** [comment]
Yes.

Are you asking on a theoretical basis? I think I have seen some work related to this, but don't remember currently. Also, not sure if this is the best place to ask. Maybe [Reddit ML](https://www.reddit.com/r/MachineLearning) or so is better.

Or Are you asking about RETURNN in particular, and you want to implement some specific method? Can you link the paper which you want to implement?

**Comment by MartinLichtblau** [comment]
Indeed, Reddit ML seems to be more fitting for such a general question. I thought you might have tried it yourself, judging from your paper [Improved training of end-to-end attention models for speech recognition](https://arxiv.org/pdf/1805.03294v1.pdf). 
I just wonder why text and speech are kept distinct in AI and NLP, although humans start learning the semantics of language purely through speech.
