### ISSUE TITLE
LM fusion with for ctc model

### ISSUE THREAD

**Issue by abhigarg-iitk** [rwth-i6/returnn-experiments#17]
I have trained a ctc model for Libri-Speech, the model config is similar to the encoder of this config

https://github.com/rwth-i6/returnn-experiments/blob/master/2018-asr-attention/librispeech/full-setup-attention/returnn.config

I want to know 2 things
1. How do I get beam search output during inference? (Something Similar to https://github.com/rwth-i6/returnn-experiments/blob/master/2018-asr-attention/librispeech/full-setup-attention/tools/search.py)
2. How can I combine it with the LM? (Is there any way provided by returnn?) 

My efforts in these directions as of now are
1. I'm able to get beam output by using tf.nn.ctc_beam_search_decoder inside ctc layer and then pulling this operation with a script similar to get-attention-weights.py. I want to know if there's a better way?
2. I can't find any good solution for this problem apart from using some external beam search decoder code.

Thanks a lot in advance.

**Comment by albertz** [comment]
Multiple things:
* E.g. `CtcLoss` and related code just wraps whatever TF provides. TF also provides `ctc_beam_search_decoder` as you mention, but that is without LM fusion. So far that I know, TF does not support CTC beam search with a LM. But as you mention, I have seem some code elsewhere which basically adds this to TF. I think you might find it in Mozilla DeepSpeech. This probably is the simplest way, to adapt this.
* We usually use our RASR software to perform decoding with hybrid HMM/NN models. CTC is just a special case of a HMM, so you can use RASR to do the CTC beam search, also with a language model. But getting this to work is non-trivial, and requires quite some effort.

**Comment by albertz** [comment]
Not sure if there is an issue here on this repository, so I'm closing this. If you think there is some bug in RETURNN, please report for that repository.
