### ISSUE TITLE
n-gram shallow fusion

### ISSUE THREAD

**Issue by deep-speech** [rwth-i6/returnn-experiments#18]
Your paper mentions shallow fusion of n-gram LM with end to end model, are the experiment details available in the repo?

**Comment by albertz** [comment]
[This](https://github.com/rwth-i6/returnn-experiments/blob/master/2018-asr-attention/librispeech/attention/exp3.ctc.lmbpe3gr.config) is one of the configs.

**Comment by albertz** [comment]
Closing now. Feel free to ask further questions.
