### ISSUE TITLE
some questions about lm config file

### ISSUE THREAD

**Issue by wencome** [rwth-i6/returnn-experiments#2]
thanks for helping me answer these two questions：
1)
returnn-experiments/2018-asr-attention/librispeech/lm/i512_m2048_m2048.sgd_b64_lr0_cl2.newbobabs.d0.2.config

line26: cached_fn = check_output(["cf", filename]).strip().decode("utf8")

what does the "cf" mean in this line?

2)
when I rnn the returnn with this config file, it reports the following error:
"CalledProcessError: Command '['cf', 'data/librispeech/lm_bpe/dev.clean.other.bpe.txt.gz']' returned non-zero exit status 1"

What is the cause of this?

Looking forward to your reply!

**Comment by albertz** [comment]
This is our [Cache manager tool](https://github.com/pavelgolik/cache-manager).
You do not need to use it. You can replace the line by:

    cached_fn = filename

**Comment by wencome** [comment]
it works! thanks!
