### ISSUE TITLE
option to provide fp16 for layer weights

### ISSUE THREAD

**Issue by ragnarlbrok** [rwth-i6/returnn-experiments#24]
is their an option to specify in returnn configs for initializing  layer weights as floating point 16  instead of floating point 32? or could it be modified in returnn code somehow? I need it for testing model optimization.

**Comment by albertz** [comment]
Yes, in principle, this is possible. Via `extern_data` in the config, you can specify `"dtype": "float16"`. Or you could make an extra layer in the config, via `EvalLayer`, and there just `tf.cast(source(0), tf.float16)`, and `"out_type": {"dtype": "float16}`.
Note that this is not well tested, and I assume there are many smaller things which would need some smaller fixes (mostly that some code hardcodes float32 as output dtype). I guess you just should try out and fix any problems step by step.

**Comment by ragnarlbrok** [comment]
ok, that explains method for conversion of input/output. is there any way to do same for layer weights & biases also?

**Comment by albertz** [comment]
I assume this is even more hardcoded at certain places. E.g. I was just checking `LinearLayer`, and it is hardcoded in there.
Maybe look at `LayerBase.var_creation_scope`, though. Maybe you can just always overwrite float32 -> float16 in there somehow.

**Comment by ragnarlbrok** [comment]
Ok, thank you.

**Comment by albertz** [comment]
@curufinwe has worked on sth related. But this is more related to Returnn, not this repo here. I'm closing this now. If you want to discuss further, open a related issue in the Returnn repo.
