### ISSUE TITLE
feeding decoded output into training network

### ISSUE THREAD

**Issue by ragnarlbrok** [rwth-i6/returnn-experiments#25]
How can we use decision layer during training time? I want to use decoded beams generated from first sub network (freezed) as input into second sub network(trainable)? So my complete network have one pre-trained & one trainable network. Because "decsion" layer can be used only during search time as written in returnn code.

**Comment by albertz** [comment]
Yes, we can. :)
I'm doing that in multiple ways already. What I would recommend now is to use the extra-net mechanism. See the documentation [here](https://returnn.readthedocs.io/en/latest/api/TFNetwork.html#TFNetwork.TFNetwork.construct_extra_net). See also the very simple example [here](https://github.com/rwth-i6/returnn/blob/1b2b704c59bb469bd9b0389db8d4591afad5ba3c/tests/test_TFNetworkLayer.py#L2465). A much more complex example is [here](https://github.com/rwth-i6/returnn/blob/92400434983a20fae1c6ef834909333ab18fd263/tests/test_TFEngine.py#L1895).

Basically, when you prefix a layer with the name `"extra.search:"`, it (and all its sublayers) will have the search flag enabled, and thus you can use `ChoiceLayer` or `DecideLayer` and they operate like in search. Note, for a `RecLayer`, if you just want to use its decoded output, and do not need to backpropagate through the search, then you should explicitly disable the back-propagation mechanism for the `RecLayer`, via `"back_prop": False` (only for the layer where you do the search, and don't need to backpropagate through), as this makes it much faster and more memory efficient.

**Comment by ragnarlbrok** [comment]
Ok, thanks. I will look into the document.

**Comment by albertz** [comment]
Closing this now. Please comment further if sth is unclear.
