### ISSUE TITLE
N-best hyps

### ISSUE THREAD

**Issue by akshatdewan** [rwth-i6/returnn-experiments#29]
Hello, 
I am sorry for a probably silly question but is there a parameter that I could specify to output n-best instead of 1-best hypothesis? I was using the tools/search.py which just calls returnn/rnn.py with --task search. And in rnn.py implementation I could not find a parameter like nbest. Thanks!

**Comment by albertz** [comment]
There is no such parameter. You simply specify what output you want to get (via option `search_output_layer`). At the moment, I assume you have sth like `search_output_layer = "decision"`, and that layer is defined as `"decision": {"class": "decide", "from": ["output"], ...}`. The `DecideLayer` (`"class": "decide"`) will pick the 1st best from the N-best list. Just do `search_output_layer = "output"` to get the N-best list directly.

**Comment by akshatdewan** [comment]
Awesome! Thanks!
