### ISSUE TITLE
some questions about lm config file

### ISSUE THREAD

**Issue by wencome** [rwth-i6/returnn-experiments#3]
I hope to reproduce the results in this great paper: “Improved training of end-to-end attention models for speech recognition”.

I need to train 2 models: 1)the seq2seq model 2)an external LM，and they use the same vocabulary file.

I want to know which corpus is used to generate the vocabulary file("trans.bpe.vocab.lm.txt")
Is it from the voice tagging corpus(only 40M)，
or from the corpus of external LM(eg:librispeech corpus file is 4G)

I hope I have expressed it clearly. Looking forward to your reply, thanks.

**Comment by albertz** [comment]
Thanks for the interest in our work!
For LibriSpeech, the full setup to download the data, prepare it, create BPE codes + vocab, train the seq2seq model is [here](https://github.com/rwth-i6/returnn-experiments/tree/master/2018-asr-attention/librispeech/full-setup-attention) (excluding the LM currently; although the [LM training config is here](https://github.com/rwth-i6/returnn-experiments/blob/master/2018-asr-attention/librispeech/lm/i512_m2048_m2048.sgd_b64_lr0_cl2.newbobabs.d0.2.config)). That should answer how to train the seq2seq model and everything about the BPE.
The LM data is the [official data for the LM](http://www.openslr.org/11/). The same BPE as in training the seq2seq model is used for the LM. (@kazuki-irie might be able to give additional details, as he trained the LM.)

**Comment by wencome** [comment]
Appreciate your help!
LM now can be trained normally, except that `"multiprocessing = True"` does not seem to take effect.
