### ISSUE TITLE
The training or Server demo will occupy all resources of one single GPU

### ISSUE THREAD

**Issue by yanghongjiazheng** [rwth-i6/returnn-experiments#31]
My friends, thanks for your great work. I have a question wondering  if you can give me the right answer. When I execute the  "22_train.sh" or "31a_start_demo_server.sh", I find that the model just occupy all the resources of one single GPU.  How can I control the occupying rate?

**Comment by albertz** [comment]
This is not really RETURNN related, this is due to how TensorFlow uses the GPU. See for example [here](https://stackoverflow.com/questions/34199233/how-to-prevent-tensorflow-from-allocating-the-totality-of-a-gpu-memory). E.g. I think sth like this in your config should work:
```
tf_session_opts = {"gpu_options": {"per_process_gpu_memory_fraction": 0.333}}
```
