### ISSUE TITLE
Implementation of MoChA for ASR

### ISSUE THREAD

**Issue by manish-kumar-garg** [rwth-i6/returnn-experiments#33]
Is this the config for implementing MoChA - Monotonic Chunkwise Attention?
`2019-asr-local-attention/librispeech/local-heuristic.argmax.win02.exp3.ctc.config`

**Comment by albertz** [comment]
No, that config corresponds to the model we describe in the paper [An analysis of local monotonic attention variants](https://www-i6.informatik.rwth-aachen.de/publications/download/1118/MerboldtAndreZeyerAlbertSchl%FCterRalfNeyHermann--Ananalysisoflocalmonotonicattentionvariants--2019.pdf). It's much simpler than MoChA. We currently do not have created a config for MoChA.

**Comment by manish-kumar-garg** [comment]
Thanks @albertz for clarifying.
How can I use this model for online decoding? Is there any implementation already available?

**Comment by albertz** [comment]
No, not really. The encoder in that config is also still a BLSTM. You would have to change it to become a unidirectional LSTM, or some other online model (e.g. LC BLSTM, or chunked BLSTM, or unidir Transformer encoder, or CNN, ...), and you probably need some tuning first to get good performance. Then you would need to develop some decoding pipeline where you can stream new audio in, run the encoder on that new audio, and successively output new hypotheses. We are working on sth like that, but it's not ready and not published, and there is no timeline. But if you invest some work into it yourself, it might actually not be too complicated.

**Comment by manish-kumar-garg** [comment]
Got it. Thanks!
