### ISSUE TITLE
query regarding lm_fusion_config

### ISSUE THREAD

**Issue by ragnarlbrok** [rwth-i6/returnn-experiments#37]
Hi guys, I am using https://github.com/rwth-i6/returnn-experiments/blob/master/2018-asr-attention/librispeech/attention/exp3.ctc.lm.config for lm_fusion on my custom dataset. Without lm_fusion hyps are good. But with lm_fusion for some utterances hyp predicted is too long & mainly repeating last symbols of utterances. it's happening with only few utterances. 
for ex:
ref: play bi@@ king in ch@@ ob@@ k
hyp: play bi@@ king in show book
hyp_fusion: play bi@@ king in show bo@@ k bo@@ k bo@@ k bo@@ k bo@@ k bo@@ k bo@@ k bo@@ k
Any pointers to debug this issue?

**Comment by albertz** [comment]
This has been observed by other people in the research community / literature, and seems to be a general problem for the encoder-decoder-attention architecture. There are several heuristics/workarounds which can reduce the problem to some degree.

Did you tune the LM scale properly?

E.g. look at [this config](https://github.com/rwth-i6/returnn-experiments/blob/master/2019-lm-transformers/librispeech/bpe_10k/base3.retrain2.transfo_lm.fusion_eval4.gamma1.1.config) (but this is actually the other way around, it penalizes EOS; although when you also tune the LM scale again with this, it might be better overall).

Some people (mostly Google) also add some coverage term (which can penalize both ways, i.e. if there was too less attention on some part of the input, but also too much attention on some part of the input).

Maybe @kazuki-irie has some more input on this.

**Comment by ragnarlbrok** [comment]
Regarding LM scale, this problem comes above LM scale > 0.1 in my cases. But LM scale above 0.1 also gives significant improvements in WER, but such types of long predictions dilute their effects. I have also tried transformer LM fusion with above mentioned EOS penilization, but problem persists in that case too. I have tried this approach in fusion_eval4 function: while fusing am_score & lm_score. if am_score have highest probability for 'EOS' symbol then only consider am_score otherwise consider am_score + lm_score*lm_scale, but this approach is also not working.

**Comment by kazuki-irie** [comment]
>  I have also tried transformer LM fusion with above mentioned EOS penilization, but problem persists in that case too.

The EOS penalty is also tunable (`gamma` in `fusion_eval4`).
You should be able to penalize longer sentences more by increasing the penalty value in the config (`1.5` instead of the default `1.1`, for example).
I do not know if you have tried that.

Another source of the problem could be the quality of the language model itself.
If the model was trained on long sequences (or not properly trained with the sentence end symbol, or not well trained in general), we tend to get this effect more likely...

**Comment by ragnarlbrok** [comment]
I have not tried large value of gamma, i will try that too. 

> Another source of the problem could be the quality of the language model itself.
> If the model was trained on long sequences (or not properly trained with the sentence end symbol, or not well trained in general), we tend to get this effect more likely...

LM is trained on similar length sentences & with proper EOS symbol as well. 
I was debugging the issue by printing am_score, lm_score, combo_score value of fusion_eval4 function with tf.Print(). If I am correct, this function applies fusion at each symbol prediction step and am_score & lm_scores are scores at a step, not the aggregated scores. but it printed more values then number of symbols it predicted. Can you explain this behaviour? Maybe some kind of other heuristics can be applied there to avoid long sentences. I have tried one too of considering only am_score at certain step(when 'EOS' is most probable), but that did not work.

**Comment by kazuki-irie** [comment]
> it printed more values then number of symbols it predicted. Can you explain this behaviour?

I do not know what exactly you printed out but anyway, I have impression that you did not take into consideration the beam size. Did you?

FYI, if you set `debug_print_layer_output_shape = True` in your config, you can get a shape summary in the log for each layer. That might help you when you are not sure about shapes...

**Comment by ragnarlbrok** [comment]
I already have debug_print_layer_output_shape = True in my config as suggested earlier by @albertz , I have tested printing scores in fusion_eval4 function with only single utterence. shape of each printed score was (beam_size=4,vocab_size), so I am assuming it printed a list of all possible beam_size scores distribution at each step. So I am not sure why printed values are more then predicted.

**Comment by ragnarlbrok** [comment]
I tried with gamma=1.5 and higher. problem still exists.

**Comment by ragnarlbrok** [comment]
there is self._debug_out in ChoiceLayer code. i have set it  to [], to store beam logs at each step, but it's not printing anything on config run? can you help with it? do i have to add something in config to enable these logs?

**Comment by albertz** [comment]
`ChoiceLayer. _debug_out` is not really supported anymore (it might still work, but really you need to check the code, I don't know).

There is the script `tools/debug-dump-search-scores.py` which should give you what you want. If you want to debug more deeply into it, see how that script works. That should give you an idea how you can debug it.

A very crude/simple way to debug would be to just add some `tf.Print` inside the loop.

**Comment by ragnarlbrok** [comment]
ok, thanks.

**Comment by ragnarlbrok** [comment]
I saw some of papers related to LM fusion, I got to know that adding coverage penalty term helps in promoting long sequences i.e improving incomplete hypothesis but also helps in removing or reducing babbling effect, maybe similar to my problem. Tensorflow has built-in integration to coverage penalty weight in BeamSearchDecoder class. can you guide how can i integrate it in returnn & check it's effect?

**Comment by albertz** [comment]
One possibility is just very similar as in [the config I already linked](https://github.com/rwth-i6/returnn-experiments/blob/master/2019-lm-transformers/librispeech/bpe_10k/base3.retrain2.transfo_lm.fusion_eval4.gamma1.1.config). See `fusion_eval4` there, and how it is used. That is just for the log linear combination of LM and acoustic model (shallow fusion), which is calculated in the EvalLayer `combo_output_log_prob`. You can simply extend that by the coverage penalty term.

The ChoiceLayer also has the argument `custom_score_combine`, which gives you some more flexibility, if you need to. See [this config as an example](https://github.com/rwth-i6/returnn-experiments/blob/master/2019-monotonic-latent-attention/switchboard/hard-att-imp3.textend.trecombtrain.attwl01.base2.conv2l.specaug4a.config). ChoiceLayer also has the argument `explicit_search_sources` which you can use to make additional information (such as a coverage term) available to the ChoiceLayer, which you can then use in your `custom_score_combine`.
But maybe the first option I outlined before (like `fusion_eval4`) is already fine and easier for your case.

**Comment by albertz** [comment]
@kazuki-irie maybe you tried the coverage penalty term already, and have some example code?
But otherwise, I think it should be straight-forward to calculate this. You might need the accumulated attention weights. You can use the already existing ones, which include the inverted-fertility term, though. But you can also just calculate the pure accumulated att weights in the same way.

**Comment by ragnarlbrok** [comment]
@albertz, I will implement coverage penalty through fusion_eval4 as you suggested & will check its effect. Can you give reference paper link for https://github.com/rwth-i6/returnn-experiments/blob/master/2018-asr-attention/librispeech/full-setup-attention/returnn.config implementation?

**Comment by albertz** [comment]
It's all documented there [in the readme](https://github.com/rwth-i6/returnn-experiments/blob/master/2018-asr-attention/librispeech/full-setup-attention/README.md). What else do you need?

**Comment by ragnarlbrok** [comment]
In implementing coverage penalty in fusion_eval4 function i require finished status of each beam also, how can i access that? As coverage penality is applied only on finished beams.

**Comment by albertz** [comment]
It's better to not apply it only on the finished beams, but all the time.

**Comment by ragnarlbrok** [comment]
I have tried that already, but that is introducing babbling effect in all sentences. and in tensorflow implementation is applied only on finished beams.here is the link beam_search_decoder.py

**Comment by albertz** [comment]
Ah, but this is done during beam search, when you look at that code. (It's inside `_get_scores`, which is used inside `_beam_search_step`.)
In the [config I linked already](https://github.com/rwth-i6/returnn-experiments/blob/master/2019-monotonic-latent-attention/switchboard/hard-att-imp3.textend.trecombtrain.attwl01.base2.conv2l.specaug4a.config), you will see how you get this `finished` tensor (`end_flags` in that config).
