### ISSUE TITLE
Enhancement Request: Include training time in Readme

### ISSUE THREAD

**Issue by manish-kumar-garg** [rwth-i6/returnn-experiments#38]
@albertz Can you include training time for various experiments you did. It would give an idea on how much time will be required for experiments.

**Comment by albertz** [comment]
Yes, would be nice. It's a bit hard to redo that for all setups in here now (although normally our training times are often 1-5 days or so; in only some of the rare extreme cases you get sth like 2 weeks; all of that always on a single GTX 1080 Ti GPU). What experiments are you mostly interested in? Maybe I can add it to those.
