### ISSUE TITLE
query regarding LM data preprocessing

### ISSUE THREAD

**Issue by ragnarlbrok** [rwth-i6/returnn-experiments#45]
Hi @albertz, in returnn lm config what does batch_size, max_seq_length, max seqs refer to? In my understanding batch_size should be max bpe symbols in a batch, similar should be max_seq_length, max_seqs should be maximum number of sentences in a batch. Is my understanding correct? I saw that in librispeech bpe_train data there are many sentences with length ~500. so how those sentences are handled? are they ignored or go into batches with fewer sentences?

**Comment by albertz** [comment]
Please check [our documentation](https://returnn.readthedocs.io/).
`batch_size` is the max number of frames in the batch (max for input frames and output labels).
`max_seq_length` is the max number of frames for a single sequence in the batch (again input/output, or depending how it is specified) (I think the config you mean (you did not link it...), it is just for the output labels.) 
`max_seqs` is the max number of sequences in the batch.

**Comment by albertz** [comment]
I'm closing now. There is no real bug or anything...
