### ISSUE TITLE
Explanation of the ASR loss averaging

### ISSUE THREAD

**Issue by smolendawid** [rwth-i6/returnn-experiments#5]
I am looking for the explanation of the following case (it's hard for me to find it in the code).
After calculating the ce loss in the ASR, the loss is accumulated over all the timesteps of the decoder. My question is: is this loss averaged over the timesteps or not, before the optimizer step? Where can I find it in the code?

Thank you

**Comment by albertz** [comment]
There is the `Loss` class (in `TFNetworkLayer`), which is the base class for any kind of loss, also the CE loss (`CrossEntropyLoss` class).
It has an option `use_normalized_loss`. If it is `True`, it will divide the accumulated loss by the number of frames. If it is `False`, it will leave the accumulated loss as-is.

**Comment by smolendawid** [comment]
Thank you
