### ISSUE TITLE
2018-asr-attention/librispeech/attention/exp3.ctc.lm.config: target 'bpe' unknown

### ISSUE THREAD

**Issue by Johannes0Horn** [rwth-i6/returnn-experiments#50]
Hello,

i modified the` returnn-experiments/2018-asr-attention/librispeech/full-setup-attention/` pipeline to train an encoder-attention-decoder system on [MEGS](https://github.com/german-asr/megs).
The result was a WER of ~20%. To improve the WER i wanted to combine it with a language model.
So i modified [the 2018-asr-attention/librispeech/lm/i512_m2048_m2048.sgd_b64_lr0_cl2.newbobabs.d0.2.config](https://github.com/rwth-i6/returnn-experiments/blob/master/2018-asr-attention/librispeech/lm/i512_m2048_m2048.sgd_b64_lr0_cl2.newbobabs.d0.2.config) to train a language model on MEGS.

The [2018-asr-attention/librispeech/lm/README](https://github.com/rwth-i6/returnn-experiments/blob/master/2018-asr-attention/librispeech/lm/README.md) says one should modify[ the 2018-asr-attention/librispeech/attention/exp3.ctc.lm.config](https://github.com/rwth-i6/returnn-experiments/blob/master/2018-asr-attention/librispeech/attention/exp3.ctc.lm.config) to combine the language model with the encoder-attention-decoder system.
Doing so and running an inference leads for me to this error:

```
  File "/home/returnn_testenv/TFNetworkLayer.py", line 970, in _static_get_target_value
    line: assert network.extern_data.has_data(target), "target %r unknown" % target
    locals:
      network = <local> <TFNetwork '<network via transform_config_dict>' parent_net=<TFNetwork 'root' train=False search> train=False>
      network.extern_data = <local> <ExternData data={'classes': Data(name='classes', shape=(None,), dtype='int32', sparse=True, dim=10045, available_for_inference=False, batch_shape_meta=[B,T|'time:var:extern_data:classes']), 'data': Data(name='data', shape=(None, 40), batch_shape_meta=[B,T|'time:var:extern_data:data',F|40])}>
      network.extern_data.has_data = <local> <bound method ExternData.has_data of <ExternData data={'classes': Data(name='classes', shape=(None,), dtype='int32', sparse=True, dim=10045, available_for_inference=False, batch_shape_meta=[B,T|'time:var:extern_data:classes']), 'data': Data(name='data', shape=(None, 40), batch_shape_meta=[B,T|'ti...
      target = <local> 'bpe'
AssertionError: target 'bpe' unknown
```
The reason for the error is that the target "bpe" is not part of the networks extern data.

The extern data looks like this:

`<ExternData data={'classes': Data(name='classes', shape=(None,), dtype='int32', sparse=True, dim=10045, available_for_inference=False, batch_shape_meta=[B,T|'time:var:extern_data:classes']), 'data': Data(name='data', shape=(None, 40), batch_shape_meta=[B,T|'time:var:extern_data:data',F|40])}>`

Im am a little bit lost at this point. Has anyone any idea whats the actual problem?
Thanks in advance!

**Comment by albertz** [comment]
Hi,

That's an interesting task. It's 536h training data? Or how much? I don't quite understand how to read the table.

I would recommend a new data preparation pipeline. It's kind of similar to 2018-asr-attention (to the latest version, in Ogg Zip format), but cleaned up, and more generic (it uses the `OggZipDataset`, and not `LibriSpeechCorpus`).
It's [2020-librispeech-data-prepare](https://github.com/rwth-i6/returnn-experiments/tree/master/2020-librispeech-data-prepare).

How did you do the data preparation? Which dataset in RETURNN did you use? Different dataset might use different data-keys. E.g. in the `SprintDataset`, it's called `"bpe"`, and in many other datasets, it's called `"classes"`. Depending what the dataset provides, you need to configure the corresponding data-keys in your config (via `num_outputs`, or via `extern_data`), and then also use the right target.

More specifically, in your current config:
* You probably have `target = "bpe"` somewhere, but your extern-data is configured such that there is `"classes"`, not `"bpe"`. So just change it to `target = "classes"`.
* Or maybe, you configured your extern-data (via `num_outputs` or `extern_data`) wrong. You maybe have `num_outputs = {..., "classes": ...}`. Just change `"classes"` to `"bpe"`.

Which variant is correct depends on your dataset class (some provide `"bpe"`, most provide `"classes"`).

**Comment by albertz** [comment]
Btw, what is your attention baseline config? The exp3.ctc is old (from 2018). I would suggest to use some of the configs from [2019-asr-e2e-trafo-vs-lstm](https://github.com/rwth-i6/returnn-experiments/tree/master/2019-asr-e2e-trafo-vs-lstm).

**Comment by christophmluscher** [comment]
No answer. Closed for now.
