### ISSUE TITLE
Convergence term

### ISSUE THREAD

**Issue by abhigarg-iitk** [rwth-i6/returnn-experiments#6]
In the original paper for Shallow Fusion (https://arxiv.org/abs/1612.02695), the authors used a convergence term to achieve better results.

Did you guys also try it? 

If yes where there any improvements and can you share the corresponding config.

**Comment by albertz** [comment]
Which convergence term do you mean? In the whole paper, I do not find any mentioning of "convergence term".
@kazuki-irie did the shallow fusion experiments. Maybe he can also help.

**Comment by abhigarg-iitk** [comment]
Sorry for my mistake. I misspelled it. It should be the "coverage term"

**Comment by albertz** [comment]
Yes, we have something like that. It is usually called attention weight feedback, and we also use a fertility term. This is described in the paper. The config is linked in the paper, and you can find it here in this repository. We also tried without that, and in many cases, the training becomes more unstable and worse.
