### ISSUE TITLE
Returnn doing layer optimizations

### ISSUE THREAD

**Issue by abhigarg-iitk** [rwth-i6/returnn-experiments#7]
I was trying to debug some model I implement in returnn, for which I needed attention and rnn output of each timestamp

For this, I created a new layer with this line
```
 "att_debug": {"class": "copy", "from": ["prev:att_debug", "att"]},  # (B, H*V)
```
and adding it after this [line]( https://github.com/rwth-i6/returnn-experiments/blob/master/2018-asr-attention/librispeech/full-setup-attention/returnn.config#L128) 

Later I was planning to add att_debug to [fetch dictonary](https://github.com/rwth-i6/returnn/blob/master/TFEngine.py#L93)

But I was not able to find att_debug anywhere in the network topology. If I do

```
print( self.engine.network.layers["output"].cell.net.layers.keys() )
```
in this [funciton](https://github.com/rwth-i6/returnn/blob/master/TFEngine.py#L93), it doesn't show att_debug.

I think somehow returnn is optimizing out this layer as it is not needed for the loss calculation.

I have tried various things like setting "optimize_move_layers_out" to False , but was not successful.

Is there a way to turn off optimizations in returnn ?

Thanks in advance

**Comment by albertz** [comment]
If the layer is nowhere used, it will not be added.
If you add `is_output_layer=True` to it, you can enforce it.
(`optimize_move_layers_out=True` should work, and even probably better.)

See also `tools/get-attention-weights.py` for an example, which does very much what you want.

**Comment by abhigarg-iitk** [comment]
Thanks a lot for this great framework and quick reply. I'll use `is_output_layer=True` for now and also look into `tools/get-attention-weights.py`

**Comment by abhigarg-iitk** [comment]
Hey Albertz,

I was trying to output some variables from the output layer inside output layer. But I was unable to figure out how to access that layer.

I tried 
`network.layers['output'].cell.net.layers.keys()`
`network.layers['output'].output`
but using none of these worked.

Thanks in Advance

**Comment by albertz** [comment]
Can you post the output of the log where it says which layers are optimized
out of the loop?

Then, on the cell object, there is also input_net and output_net (or so).
If you specified is_output_layer, you should find the sublayer in any case
in output_net.

The sub layer however night not have the variables. But the output layer
itself has them all (params or so).


Am Di., 30. Okt. 2018, 14:38 hat Abhinav Garg <notifications@github.com>
geschrieben:
