### ISSUE TITLE
Big files in repo

### ISSUE THREAD

**Issue by albertz** [rwth-i6/returnn-experiments#76]
RASR executables, maybe other stuff.

For example in `2021-ADSM` (@ZhouW321).

Should be removed. On Slack we agreed that rewriting the Git history in this (exceptional!) case is ok (for this repo here only!).

**Comment by ZhouW321** [comment]
executables removed, anything else ?

**Comment by albertz** [comment]
Yes the Git history now needs to be rewritten, as explained.

**Comment by ZhouW321** [comment]
maybe I don't understand, isn't this the same eventually ?

**Comment by albertz** [comment]
For reference, this is even explained in the [GitHub docs](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github#removing-a-file-that-was-added-in-an-earlier-commit). But as we discussed, I will do that.

**Comment by albertz** [comment]
I now cleaned it up using [BFG](https://rtyley.github.io/bfg-repo-cleaner/), with a limit of 3MB for files (basically just `bfg -b 3M`).

This means that I now changed the master branch history.

This means, next time you pull in an existing cloned repo, you might see sth like:
```
$ git pull
remote: Enumerating objects: 57, done.
remote: Counting objects: 100% (57/57), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 57 (delta 18), reused 57 (delta 18), pack-reused 0
Unpacking objects: 100% (57/57), 8.40 KiB | 477.00 KiB/s, done.
From github.com:rwth-i6/returnn-experiments
 + a0ca3bf...a2c804a master     -> origin/master  (forced update)
hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
fatal: Need to specify how to reconcile divergent branches.
```

I did `git pull -r` and that worked. I.e. afterwards, `git status` displays:
```
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```
This is important. You should **not** see any new things to be committed there. Your branch should be up to date now.

I'm not sure if `git pull -r` always works or whether it might reintroduce the bad files in some cases, or break in other cases. Double check `git status`.

If this somehow does not work for you, just clone the repo again.

In the future, please always check that you are not adding big files.
(Maybe we can enforce this. See #77.)
